import { useMemo } from 'react'

export default function useLightboxImages(type) {
  const images = useMemo(() => lightboxImages[type] || [], [type])
  return images
}


const lightboxImages = {
  product: [
    { src: './imgs/images/product/1.jpg', alt: 'product1' },
    { src: './imgs/images/product/2.jpg', alt: 'product2' },
    { src: './imgs/images/product/3.jpg', alt: 'product3' },
    { src: './imgs/images/product/4.jpg', alt: 'product4' },
    { src: './imgs/images/product/5.jpg', alt: 'product5' },
    { src: './imgs/images/product/6.jpg', alt: 'product6' },
    { src: './imgs/images/product/7.jpg', alt: 'product7' },
    { src: './imgs/images/product/8.jpg', alt: 'product8' },
    { src: './imgs/images/product/9.jpg', alt: 'product9' },
    { src: './imgs/images/product/10.jpg', alt: 'product10' },
    { src: './imgs/images/product/11.jpg', alt: 'product11' },
    { src: './imgs/images/product/12.jpg', alt: 'product12' },
    { src: './imgs/images/product/13.jpg', alt: 'product13' },
    { src: './imgs/images/product/14.jpg', alt: 'product14' },
    { src: './imgs/images/product/15.jpg', alt: 'product15' },
    { src: './imgs/images/product/16.jpg', alt: 'product16' },
    { src: './imgs/images/product/17.jpg', alt: 'product17' },
    { src: './imgs/images/product/18.jpg', alt: 'product18' },
    { src: './imgs/images/product/19.jpg', alt: 'product19' },
    { src: './imgs/images/product/20.jpg', alt: 'product20' },
    { src: './imgs/images/product/21.jpg', alt: 'product21' },
  ],
  luxury: [
    { src: './imgs/images/luxury/1.jpg', alt: 'luxury1' },
    { src: './imgs/images/luxury/2.jpg', alt: 'luxury2' },
    { src: './imgs/images/luxury/3.jpg', alt: 'luxury3' },
    { src: './imgs/images/luxury/4.jpg', alt: 'luxury4' },
    { src: './imgs/images/luxury/5.jpg', alt: 'luxury5' },
    { src: './imgs/images/luxury/6.jpg', alt: 'luxury6' },
    { src: './imgs/images/luxury/7.jpg', alt: 'luxury7' },
    { src: './imgs/images/luxury/8.jpg', alt: 'luxury8' },
    { src: './imgs/images/luxury/9.jpg', alt: 'luxury9' },
    { src: './imgs/images/luxury/10.jpg', alt: 'luxury10' },
    { src: './imgs/images/luxury/11.jpg', alt: 'luxury11' },
    { src: './imgs/images/luxury/12.jpg', alt: 'luxury12' },
    { src: './imgs/images/luxury/13.jpg', alt: 'luxury13' },
    { src: './imgs/images/luxury/14.jpg', alt: 'luxury14' },
    { src: './imgs/images/luxury/15.jpg', alt: 'luxury15' },
    { src: './imgs/images/luxury/16.jpg', alt: 'luxury16' },
  ],
  event: [
    { src: './imgs/images/event/1.jpg', alt: 'event1' },
    { src: './imgs/images/event/2.jpg', alt: 'event2' },
    { src: './imgs/images/event/3.jpg', alt: 'event3' },
    { src: './imgs/images/event/4.jpg', alt: 'event4' },
    { src: './imgs/images/event/5.jpg', alt: 'event5' },
    { src: './imgs/images/event/6.jpg', alt: 'event6' },
    { src: './imgs/images/event/7.jpg', alt: 'event7' },
    { src: './imgs/images/event/8.jpg', alt: 'event8' },
    { src: './imgs/images/event/9.jpg', alt: 'event9' },
    { src: './imgs/images/event/10.jpg', alt: 'event10' },
    { src: './imgs/images/event/imin/1.jpg', alt: 'event/imin1' },
    { src: './imgs/images/event/imin/2.jpg', alt: 'event/imin2' },
    { src: './imgs/images/event/imin/3.jpg', alt: 'event/imin3' },
    { src: './imgs/images/event/imin/4.jpg', alt: 'event/imin4' },
    { src: './imgs/images/event/imin/5.jpg', alt: 'event/imin5' },
    { src: './imgs/images/event/imin/6.jpg', alt: 'event/imin6' },
    { src: './imgs/images/event/imin/7.jpg', alt: 'event/imin7' },
    { src: './imgs/images/event/imin/8.jpg', alt: 'event/imin8' },
    { src: './imgs/images/event/imin/9.jpg', alt: 'event/imin9' },
    { src: './imgs/images/event/imin/10.jpg', alt: 'event/imin10' },
  ],
  portrait: [],
  food: [],
  streetsnap: [
    { src: './imgs/images/streetsnap/1.jpg', alt: 'streetsnap1' },
    { src: './imgs/images/streetsnap/2.jpg', alt: 'streetsnap2' },
    { src: './imgs/images/streetsnap/3.jpg', alt: 'streetsnap3' },
    { src: './imgs/images/streetsnap/4.jpg', alt: 'streetsnap4' },
    { src: './imgs/images/streetsnap/5.jpg', alt: 'streetsnap5' },
    { src: './imgs/images/streetsnap/6.jpg', alt: 'streetsnap6' },
    { src: './imgs/images/streetsnap/7.jpg', alt: 'streetsnap7' },
    { src: './imgs/images/streetsnap/8.jpg', alt: 'streetsnap8' },
    { src: './imgs/images/streetsnap/tokyo/1.jpg', alt: 'tokyo1' },
    { src: './imgs/images/streetsnap/tokyo/2.jpg', alt: 'tokyo2' },
    { src: './imgs/images/streetsnap/tokyo/3.jpg', alt: 'tokyo3' },
    { src: './imgs/images/streetsnap/tokyo/4.jpg', alt: 'tokyo4' },
    { src: './imgs/images/streetsnap/tokyo/5.jpg', alt: 'tokyo5' },
    { src: './imgs/images/streetsnap/tokyo/6.jpg', alt: 'tokyo6' },
    { src: './imgs/images/streetsnap/tokyo/7.jpg', alt: 'tokyo7' },
    { src: './imgs/images/streetsnap/tokyo/8.jpg', alt: 'tokyo8' },
    { src: './imgs/images/streetsnap/tokyo/9.jpg', alt: 'tokyo9' },
    { src: './imgs/images/streetsnap/tokyo/10.jpg', alt: 'tokyo10' },
  ],
  landscape: [
    { src: './imgs/images/landscape/1.jpg', alt: 'landscape1' },
    { src: './imgs/images/landscape/2.jpg', alt: 'landscape2' },
    { src: './imgs/images/landscape/3.jpg', alt: 'landscape3' },
    { src: './imgs/images/landscape/4.jpg', alt: 'landscape4' },
    { src: './imgs/images/landscape/5.jpg', alt: 'landscape5' },
    { src: './imgs/images/landscape/6.jpg', alt: 'landscape6' },
    { src: './imgs/images/landscape/7.jpg', alt: 'landscape7' },
    { src: './imgs/images/landscape/8.jpg', alt: 'landscape8' },
    { src: './imgs/images/landscape/9.jpg', alt: 'landscape9' },
    { src: './imgs/images/landscape/10.jpg', alt: 'landscape10' },
  ],
}
