POST http://localhost:8080/v1/contact
Content-Type: application/json

{
    "name": "Gino",
    "email": "gino7777@gmail.com",
    "url": "https://www.immortal-style.com",
    "film_type": ["commercial"],
    "description": "test",
    "start_date": "2024-01-01",
    "end_date_preference": "Y",
    "budget": 5,
    "source": ["website", "facebook"]
}